### ISSUE TITLE
Report Error

### ISSUE THREAD

**Issue by infernoshoot** [agnira/apaint#1]
Report Erro
![888](https://user-images.githubusercontent.com/29793108/161694106-3a09ecaf-1b62-4229-8f89-100241c5e708.PNG)
r

**Comment by agnira** [comment]
Hi @infernoshoot, thanks for reporting.
Have you try the last update ? I also found that error and it should fix on the last push.

**Comment by agnira** [comment]
Hi @infernoshoot, I'll close this issue because I've re check it and didn't get the same error anymore. You can re-open it when you still have the problem, and help me to recreate the error. ;)
